import SearchSetting from "@/components/search/SearchSetting";

const searchSetting: SearchSetting = {
  searchUrl: "/api/sample",
  conditions: [
    {
      kind: "select",
      label: "물품분류",
      default: "A",
      field: "select1",
      options: [
        { description: "A", value: "A" },
        { description: "B", value: "B" },
        { description: "C", value: "C" },
      ],
    },
    {
      kind: "select",
      parentField: "select1",
      default: "",
      field: "select2",
      options: [
        { description: "Aa", value: "Aa" },
        { description: "Ab", value: "Ab" },
        { description: "Ac", value: "Ac" },
        { description: "Ba", value: "Ba" },
        { description: "Bb", value: "Bb" },
        { description: "Bc", value: "Bc" },
        { description: "Ca", value: "Ca" },
        { description: "Cb", value: "Cb" },
        { description: "Cc", value: "Cc" },
      ],
    },
    {
      kind: "select",
      parentField: "select2",
      default: "",
      field: "select3",
      options: [
        { description: "Aa가", value: "Aa가" },
        { description: "Aa나", value: "Aa나" },
        { description: "Aa다", value: "Aa다" },
        { description: "Ab가", value: "Ab가" },
        { description: "Ab나", value: "Ab나" },
        { description: "Ab다", value: "Ab다" },
        { description: "Ac가", value: "Ac가" },
        { description: "Ac나", value: "Ac나" },
        { description: "Ac다", value: "Ac다" },
        { description: "Ba가", value: "Ba가" },
        { description: "Ba나", value: "Ba나" },
        { description: "Ba다", value: "Ba다" },
        { description: "Bb가", value: "Bb가" },
        { description: "Bb나", value: "Bb나" },
        { description: "Bb다", value: "Bb다" },
        { description: "Bc가", value: "Bc가" },
        { description: "Bc나", value: "Bc나" },
        { description: "Bc다", value: "Bc다" },
        { description: "Ca가", value: "Ca가" },
        { description: "Ca나", value: "Ca나" },
        { description: "Ca다", value: "Ca다" },
        { description: "Cb가", value: "Cb가" },
        { description: "Cb나", value: "Cb나" },
        { description: "Cb다", value: "Cb다" },
        { description: "Cc가", value: "Cc가" },
        { description: "Cc나", value: "Cc나" },
        { description: "Cc다", value: "Cc다" },
      ],
    },
  ],
};

export default searchSetting;
