import Conditions from "@/components/search/conditions/Conditions";

const searchSetting: Conditions = [
  {
    kind: "select",
    label: "물품분류",
    value: "A",
    field: "select1",
    options: [
      { description: "1차분류", value: "", disabled: true },
      { description: "A", value: "A" },
      { description: "B", value: "B" },
      { description: "C", value: "C" },
    ],
  },
  {
    kind: "select",
    parentField: "select1",
    value: "",
    field: "select2",
    options: [
      { description: "2차분류", value: "", disabled: true },
      { description: "Aa", value: "Aa", parent: "A" },
      { description: "Ab", value: "Ab", parent: "A" },
      { description: "Ac", value: "Ac", parent: "A" },
      { description: "Ba", value: "Ba", parent: "B" },
      { description: "Bb", value: "Bb", parent: "B" },
      { description: "Bc", value: "Bc", parent: "B" },
      { description: "Ca", value: "Ca", parent: "C" },
      { description: "Cb", value: "Cb", parent: "C" },
      { description: "Cc", value: "Cc", parent: "C" },
    ],
  },
  {
    kind: "select",
    parentField: "select2",
    value: "",
    field: "select3",
    options: [
      { description: "3차분류", value: "", disabled: true },
      { description: "Aa가", value: "Aa가", parent: "Aa" },
      { description: "Aa나", value: "Aa나", parent: "Aa" },
      { description: "Aa다", value: "Aa다", parent: "Aa" },
      { description: "Ab가", value: "Ab가", parent: "Ab" },
      { description: "Ab나", value: "Ab나", parent: "Ab" },
      { description: "Ab다", value: "Ab다", parent: "Ab" },
      { description: "Ac가", value: "Ac가", parent: "Ac" },
      { description: "Ac나", value: "Ac나", parent: "Ac" },
      { description: "Ac다", value: "Ac다", parent: "Ac" },
      { description: "Ba가", value: "Ba가", parent: "Ba" },
      { description: "Ba나", value: "Ba나", parent: "Ba" },
      { description: "Ba다", value: "Ba다", parent: "Ba" },
      { description: "Bb가", value: "Bb가", parent: "Bb" },
      { description: "Bb나", value: "Bb나", parent: "Bb" },
      { description: "Bb다", value: "Bb다", parent: "Bb" },
      { description: "Bc가", value: "Bc가", parent: "Bc" },
      { description: "Bc나", value: "Bc나", parent: "Bc" },
      { description: "Bc다", value: "Bc다", parent: "Bc" },
      { description: "Ca가", value: "Ca가", parent: "Ca" },
      { description: "Ca나", value: "Ca나", parent: "Ca" },
      { description: "Ca다", value: "Ca다", parent: "Ca" },
      { description: "Cb가", value: "Cb가", parent: "Cb" },
      { description: "Cb나", value: "Cb나", parent: "Cb" },
      { description: "Cb다", value: "Cb다", parent: "Cb" },
      { description: "Cc가", value: "Cc가", parent: "Cc" },
      { description: "Cc나", value: "Cc나", parent: "Cc" },
      { description: "Cc다", value: "Cc다", parent: "Cc" },
    ],
  },
];
export default searchSetting;
